dywee_shipment_table:
    path:     /admin6833/shipment/table/{idOrder}
    defaults: { _controller: DyweeShipmentBundle:Shipment:table }
    requirements:
        idOrder: \d+

dywee_shipment_add:
    path:     /admin6833/shipment/add
    defaults: { _controller: DyweeShipmentBundle:Shipment:add }

dywee_shipment_view:
    path:     /admin6833/shipment/view/{id}
    defaults: { _controller: DyweeShipmentBundle:Shipment:view }
    requirements:
        id: \d+

dywee_shipment_update:
    path:     /admin6833/shipment/update/{id}
    defaults: { _controller: DyweeShipmentBundle:Shipment:update }
    requirements:
            id: \d+

dywee_shipment_delete:
    path:     /admin6833/shipment/delete/{id}
    defaults: { _controller: DyweeShipmentBundle:Shipment:delete }
    requirements:
            id: \d+

dywee_shipment_label:
    path:     /admin6833/shipment/label/{id}
    defaults: { _controller: DyweeShipmentBundle:Shipment:label }
    requirements:
            id: \d+

dywee_shipment_note_download:
    path:     /admin6833/shipment/{idShipment}/download
    defaults: { _controller: DyweeShipmentBundle:Shipment:download }
    requirements:
            id: \d+

dywee_shipment_note_view:
    path:     /admin6833/shipment/{idShipment}/viewNote
    defaults: { _controller: DyweeShipmentBundle:Shipment:viewNote }
    requirements:
            id: \d+

dywee_deliver_table:
    path:     /admin6833/deliver/table
    defaults: { _controller: DyweeShipmentBundle:Deliver:table }

dywee_deliver_add:
    path:     /admin6833/deliver/add
    defaults: { _controller: DyweeShipmentBundle:Deliver:add }

dywee_deliver_view:
    path:     /admin6833/deliver/view/{id}
    defaults: { _controller: DyweeShipmentBundle:Deliver:view }
    requirements:
        id: \d+

dywee_deliver_update:
    path:     /admin6833/deliver/update/{id}
    defaults: { _controller: DyweeShipmentBundle:Deliver:update }
    requirements:
            id: \d+

dywee_deliver_delete:
    path:     /admin6833/deliver/delete/{id}
    defaults: { _controller: DyweeShipmentBundle:Deliver:delete }
    requirements:
            id: \d+

dywee_shipmentMethod_table:
    path:     /admin6833/shipmentMethod/table
    defaults: { _controller: DyweeShipmentBundle:ShipmentMethod:table }

dywee_shipmentMethod_add:
    path:     /admin6833/shipmentMethod/add
    defaults: { _controller: DyweeShipmentBundle:ShipmentMethod:add }

dywee_shipmentMethod_view:
    path:     /admin6833/shipmentMethod/view/{id}
    defaults: { _controller: DyweeShipmentBundle:ShipmentMethod:view }
    requirements:
        id: \d+

dywee_shipmentMethod_update:
    path:     /admin6833/shipmentMethod/update/{id}
    defaults: { _controller: DyweeShipmentBundle:ShipmentMethod:update }
    requirements:
            id: \d+

dywee_shipmentMethod_delete:
    path:     /admin6833/shipmentMethod/delete/{id}
    defaults: { _controller: DyweeShipmentBundle:ShipmentMethod:delete }
    requirements:
            id: \d+

dywee_shipmentMethod_search_ajax:
    path: /shipmentMethod/search
    defaults: { _controller: DyweeShipmentBundle:ShipmentMethod:searchAjax }
    requirements:
        _methods: POST