services:
    dywee_shipment.admin_sidebar_listener:
        class: Dywee\ShipmentBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_shipemnt.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_shipemnt.sidebar_handler:
        class: Dywee\ShipmentBundle\Service\ShipmentAdminSidebarHandler
        arguments: [ '@router' ]

