<?php

namespace Dywee\ShipmentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeliverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliverRepository extends EntityRepository
{
}
