<?php

namespace Dywee\ShipmentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentRepository extends EntityRepository
{
    public function findByActive(){
        $query = $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.state > 0 and s.state < 9');

        $query = $query
            ->getQuery()
            ->getResult();

        return $query;
    }
}
