<?php

namespace Dywee\ShipmentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShipmentElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentElementRepository extends EntityRepository
{
}
