<?php

namespace Dywee\ShipmentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShipmentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentMethodRepository extends EntityRepository
{
    public function findForCheckout($country, $weight, $type = null)
    {
        $queryBuilder = $this->createQueryBuilder('sm')
            ->select('sm')
            ->where('sm.country = :country or sm.country is null')
            ->andWhere('sm.active = 1')
            ->andWhere('sm.minWeight <= :weight or sm.minWeight is null')
            ->andWhere('sm.maxWeight > :weight or sm.maxWeight is null')
            ->setParameters(array(
                'country' => is_numeric($country)?$country:$country->getId(),
                'weight' => $weight
            ));

        if($type)
        {
            $queryBuilder->andWhere('sm.type = :type')
                ->setParameter('type', substr($type, 0, 3));
        }


        return $queryBuilder->getQuery()->getResult();
    }
}
