<?php

namespace Dywee\ShipmentBundle\Controller;

use Dywee\CoreBundle\Controller\ParentController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ShipmentRuleController extends ParentController
{
    /**
     * @Route(name="shipment_rule_add", path="admin/shipment/rule/add")
     */
    public function addAction(Request $request, $parameters = null)
    {
        return parent::addAction($request, $parameters); // TODO: Change the autogenerated stub
    }
}
